### ISSUE TITLE
Log timer starts and stops for each work item in another table

### ISSUE THREAD

**Issue by bennyboer** [bennyboer/worklog#13]
Log all timer starts and stops using worklog start, worklog continue, worklog pause, worklog finish.
When done, we can remove the time_taken attribute from `WorkItem` and calculate it on demand.

Additionally we are then able to calculate the total time worked on tasks even with parallel work items!

# TODO
- [x] Log all timer events in another table
- [x] Remove time_taken from `WorkItem`
- [x] Calculate time_taken on demand from the data in the new table
- [x] Calculate total time taken per day based on the timer events
- [x] Display total time taken per day when using `worklog list` and display it next to the date
